Enable:
  Default: true
  WhenSneaking: false
  WhenNotSneaking: true

CuttingInterval: 2

LimitTools: true
Cutters:
  - AIR
  - DIAMOND_AXE
  - GOLDEN_AXE
  - IRON_AXE
  - STONE_AXE
  - WOODEN_AXE

ReplantSaplings: true